kind: Deployment
apiVersion: apps/v1
metadata:
  name: diploid
  namespace: diploid
  labels:
    app: diploid
spec:
  selector:
    matchLabels:
      app: diploid
  template:
    metadata:
      labels:
        app: diploid
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ""
      containers:
      - name: diploid
        image: seeekr/diploid
        ports:
        - containerPort: 80
        env:
        - name: CONFIG_DIR
          value: /etc/diploid
        - name: SOURCE_DIR
          value: /data/diploid/source
        - name: STATE_DIR
          value: /data/diploid/state
        - name: USE_GVISOR
          value: "true"
        - name: HOOKS_TOKEN
          value: AYoi7Yvohzh2BfBJFNY3t10Ej9FbbNYi
        volumeMounts:
        - name: config
          mountPath: /etc/diploid
          readOnly: true
        - name: kubernetes-config
          mountPath: /root/.kube/admin.conf
          readOnly: true
        - name: diploid
          mountPath: /diploid
        - name: docker-sock
          mountPath: /var/run/docker.sock
      volumes:
      - name: config
        configMap:
          name: diploid-config
      - name: kubernetes-config
        hostPath:
          path: /etc/kubernetes/admin.conf
          type: File
      - name: diploid
        hostPath:
          path: /data/diploid
          type: DirectoryOrCreate
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
          type: Socket

---

kind: Service
apiVersion: v1
metadata:
  name: diploid
  namespace: diploid
  labels:
    app: diploid
spec:
  selector:
    app: diploid
  ports:
  - port: 80

---

kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: diploid
  namespace: diploid
  labels:
    app: diploid
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: true
    ingress.kubernetes.io/ssl-redirect: true
spec:
  tls:
    - hosts:
      - diploid.{{domain}}
      secretName: tls-diploid
  rules:
  - host: diploid.{{domain}}
    http:
      paths:
      - path: /
        backend:
          serviceName: diploid
          servicePort: 80
